# Generated by Django 6.0.3 on 2026-03-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='price_per_seat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
