# Generated by Django 6.0.3 on 2026-03-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_booking_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='no-email@example.com', max_length=254),
        ),
    ]
