# Generated by Django 6.0.3 on 2026-04-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
        migrations.AddField(
            model_name='bus',
            name='currency',
            field=models.CharField(choices=[('MWK', 'Malawi Kwacha (MK)'), ('ZAR', 'South African Rand (R)')], default='MWK', max_length=3),
        ),
    ]
